### ISSUE TITLE
Well the code isn't there beyond the readme.

### ISSUE THREAD

**Issue by jmdesp** [AhmedElkelesh/Genetic-Algorithm-based-LDPC-Code-Design#1]
Was really interested in reading that code, and also in the potential it has, after reading your paper.
Disappointed to see you didn't go further than posting the README, I hope it's not too difficult to correct this (PS : just the generated H-matrices would be nice already).

**Comment by HAPPYBEAR1** [comment]
Hello！I have carefully read your paper and code, and now I have a question I'd like to ask: How is the all_Hs constructed in population1 ? If I want to generate LDPC matrices of other sizes (for example: 128x1024, 256x1024, etc.), how should I generate the initial population?
I would be very grateful indeed for any help you could give me.
